import Vue from 'vue'
import { Button, NavBar, Field, CellGroup, Icon, Cell, Toast, Dialog, Tab, Tabs, Popup, DatetimePicker, Picker, Progress, Swipe, SwipeItem, Checkbox, Stepper, Radio, RadioGroup, Uploader, Area, Switch } from 'vant'
Vue
  .use(Button)
  .use(NavBar)
  .use(Field)
  .use(CellGroup)
  .use(Icon)
  .use(Cell)
  .use(Toast)
  .use(Dialog)
  .use(Tab)
  .use(Tabs)
  .use(Popup)
  .use(DatetimePicker)
  .use(Picker)
  .use(Progress)
  .use(Swipe)
  .use(SwipeItem)
  .use(Checkbox)
  .use(Stepper)
  .use(Radio)
  .use(RadioGroup)
  .use(Uploader)
  .use(Area)
  .use(Switch)
